index:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: task_list_index
        permanent: true
        keepQueryParams: true
